### Get all products

GET http://localhost:5005/api/products

### Create new product 
POST http://localhost:5005/api/products
Constent-Type: application/json

{
    "name": "Product 1",
    "category": "Category 1",
    "quantity": 100,
    "price": 100,
    "description": "This is product 1"
}